/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Proceso;
import Model.SO;
import Model.Usuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Timer;

/**
 *
 * @author Jesus
 */
public class PanelSO extends javax.swing.JFrame implements ActionListener{
    static int delay = 51;
    private boolean encendido = false;
    
    private final Timer t = new Timer(delay, this);
    private final SO so = new SO();
    private final Usuario u = new Usuario(so);
        
    public PanelSO() {
        initComponents();
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(encendido){
            so.graficarColaProcesos(ColaProcesos,tblEjec,tblListos,tblBloqueados,tblFinal,tblHistEjec,tblHistBloqueados);
            so.generarEstadisticas(lblTiempoUso, lblTiempoOcioso, lblTiempoEspProm, lblDuracion);
            so.graficarEspacioMemoria(MemoriaRAM);
            txtPID.setText(Integer.toString(Proceso.numeroProcesos));
            validate();
        }
    }
    
    private void iniciarSimulacion(){
        if(!encendido){
            so.iniciar();
            if (chbValoresAleatorios.isSelected()) {
                u.iniciar();
            }
            t.start();
            encendido = true;
            btnPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BotonStop.jpg")));
        }else{
            t.stop();
            so.parar();
            u.parar();
            encendido = false;
            btnPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BotonPlay.jpg")));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneSO = new javax.swing.JTabbedPane();
        PanelSistemaOperativo = new javax.swing.JPanel();
        PanelConfiguracion = new javax.swing.JPanel();
        PanelSimulacion = new javax.swing.JPanel();
        chbValoresAleatorios = new javax.swing.JCheckBox();
        PanelVelocidadSimulacion = new javax.swing.JPanel();
        sldVelocidad = new javax.swing.JSlider();
        btnPlayStop = new javax.swing.JButton();
        PanelProcesos = new javax.swing.JPanel();
        lblBursTime = new javax.swing.JLabel();
        txtBurstTime = new javax.swing.JTextField();
        btnAddProceso = new javax.swing.JButton();
        lblPID = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        PanelPoliticaPlanif = new javax.swing.JPanel();
        lblAlgoritmoPlanificacion = new javax.swing.JLabel();
        cmbAlgoritmoPlanificacion = new javax.swing.JComboBox<>();
        lblTipoPolitica = new javax.swing.JLabel();
        cmbTipoPoliticaPlanif = new javax.swing.JComboBox<>();
        PoliticaConfigAdic = new javax.swing.JPanel();
        txtTimeQuantum = new javax.swing.JLabel();
        txtAsigMemoria = new javax.swing.JLabel();
        txtCapMemoria = new javax.swing.JLabel();
        cmbAsigMemoria = new javax.swing.JComboBox<>();
        spnCapMemoria = new javax.swing.JSpinner();
        spnTimeQuantum = new javax.swing.JSpinner();
        PanelColaProcesos = new javax.swing.JPanel();
        ScrollColaProcesos = new javax.swing.JScrollPane();
        ColaProcesos = new javax.swing.JPanel();
        PanelMemoriaRAM = new javax.swing.JPanel();
        ScrollMemoriaRAM = new javax.swing.JScrollPane();
        MemoriaRAM = new javax.swing.JPanel();
        PanelEstadisticas = new javax.swing.JPanel();
        lblTiempoUso = new javax.swing.JLabel();
        lblTiempoOcioso = new javax.swing.JLabel();
        lblTiempoEspProm = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelLeyendaProcesos = new javax.swing.JPanel();
        LeyendaEjec = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LeyendoListos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LeyendaBloqueados = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        LeyendaFinalizados = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LeyendaError = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PanelTablasProcesos = new javax.swing.JPanel();
        PanelEjecutando = new javax.swing.JPanel();
        ScrollEjecutando = new javax.swing.JScrollPane();
        tblEjec = new javax.swing.JTable();
        PanelListos = new javax.swing.JPanel();
        ScrollListos = new javax.swing.JScrollPane();
        tblListos = new javax.swing.JTable();
        PanelBloqueados = new javax.swing.JPanel();
        ScrollBloqueados = new javax.swing.JScrollPane();
        tblBloqueados = new javax.swing.JTable();
        Flecha1 = new javax.swing.JLabel();
        Flecha3 = new javax.swing.JLabel();
        Flecha2 = new javax.swing.JLabel();
        Flecha4 = new javax.swing.JLabel();
        PanelFinalizados = new javax.swing.JPanel();
        ScrollFinalizados = new javax.swing.JScrollPane();
        tblFinal = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        PanelTablaProcesosHistorico = new javax.swing.JPanel();
        PanelProcesosEjecutados = new javax.swing.JPanel();
        ScrollHistoricoEjec = new javax.swing.JScrollPane();
        tblHistEjec = new javax.swing.JTable();
        PanelProcesosBloqueados = new javax.swing.JPanel();
        ScrollHistoricoBloqueados = new javax.swing.JScrollPane();
        tblHistBloqueados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelConfiguracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion de Planificacion"));

        PanelSimulacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulacion"));

        chbValoresAleatorios.setText("Generar Valores Aleatorios");
        chbValoresAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbValoresAleatoriosActionPerformed(evt);
            }
        });

        PanelVelocidadSimulacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Velocidad de la simulacion"));

        sldVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVelocidadStateChanged(evt);
            }
        });

        btnPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BotonPlay.jpg"))); // NOI18N
        btnPlayStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVelocidadSimulacionLayout = new javax.swing.GroupLayout(PanelVelocidadSimulacion);
        PanelVelocidadSimulacion.setLayout(PanelVelocidadSimulacionLayout);
        PanelVelocidadSimulacionLayout.setHorizontalGroup(
            PanelVelocidadSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVelocidadSimulacionLayout.createSequentialGroup()
                .addComponent(sldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelVelocidadSimulacionLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVelocidadSimulacionLayout.setVerticalGroup(
            PanelVelocidadSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVelocidadSimulacionLayout.createSequentialGroup()
                .addComponent(sldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayStop)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelSimulacionLayout = new javax.swing.GroupLayout(PanelSimulacion);
        PanelSimulacion.setLayout(PanelSimulacionLayout);
        PanelSimulacionLayout.setHorizontalGroup(
            PanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSimulacionLayout.createSequentialGroup()
                .addComponent(PanelVelocidadSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelSimulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbValoresAleatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSimulacionLayout.setVerticalGroup(
            PanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSimulacionLayout.createSequentialGroup()
                .addComponent(chbValoresAleatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelVelocidadSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, Short.MAX_VALUE))
        );

        PanelProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos Procesos"));

        lblBursTime.setText("Burst Time");

        btnAddProceso.setText("Agregar Proceso");
        btnAddProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProcesoActionPerformed(evt);
            }
        });

        lblPID.setText("PID");

        txtPID.setEnabled(false);

        javax.swing.GroupLayout PanelProcesosLayout = new javax.swing.GroupLayout(PanelProcesos);
        PanelProcesos.setLayout(PanelProcesosLayout);
        PanelProcesosLayout.setHorizontalGroup(
            PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosLayout.createSequentialGroup()
                .addGroup(PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProcesosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelProcesosLayout.createSequentialGroup()
                        .addGroup(PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProcesosLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnAddProceso))
                            .addGroup(PanelProcesosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBursTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBurstTime, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelProcesosLayout.setVerticalGroup(
            PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBursTime)
                    .addComponent(txtBurstTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddProceso)
                .addGap(27, 27, 27))
        );

        PanelPoliticaPlanif.setBorder(javax.swing.BorderFactory.createTitledBorder("Politica de Planificacion"));

        lblAlgoritmoPlanificacion.setText("Politica");

        cmbAlgoritmoPlanificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "Round Robin", "Prioridades" }));
        cmbAlgoritmoPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoritmoPlanificacionActionPerformed(evt);
            }
        });

        lblTipoPolitica.setText("Tipo de Politica");

        cmbTipoPoliticaPlanif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apropiativo", "Expropiativo" }));
        cmbTipoPoliticaPlanif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPoliticaPlanifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPoliticaPlanifLayout = new javax.swing.GroupLayout(PanelPoliticaPlanif);
        PanelPoliticaPlanif.setLayout(PanelPoliticaPlanifLayout);
        PanelPoliticaPlanifLayout.setHorizontalGroup(
            PanelPoliticaPlanifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPoliticaPlanifLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPoliticaPlanifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPoliticaPlanifLayout.createSequentialGroup()
                        .addComponent(lblAlgoritmoPlanificacion)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAlgoritmoPlanificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPoliticaPlanifLayout.createSequentialGroup()
                        .addComponent(lblTipoPolitica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoPoliticaPlanif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelPoliticaPlanifLayout.setVerticalGroup(
            PanelPoliticaPlanifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPoliticaPlanifLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelPoliticaPlanifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlgoritmoPlanificacion)
                    .addComponent(cmbAlgoritmoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(PanelPoliticaPlanifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPolitica)
                    .addComponent(cmbTipoPoliticaPlanif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        PoliticaConfigAdic.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuraciones Adicionales"));

        txtTimeQuantum.setText("Tiempo Quantum");

        txtAsigMemoria.setText("Asignacion Memoria");

        txtCapMemoria.setText("Capacidad Memoria");

        cmbAsigMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero hueco", "Mejor hueco", "Peor hueco" }));
        cmbAsigMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsigMemoriaActionPerformed(evt);
            }
        });

        spnCapMemoria.setValue(2000);
        spnCapMemoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCapMemoriaStateChanged(evt);
            }
        });

        spnTimeQuantum.setToolTipText("");
        spnTimeQuantum.setEnabled(false);
        spnTimeQuantum.setValue(10);
        spnTimeQuantum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTimeQuantumStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PoliticaConfigAdicLayout = new javax.swing.GroupLayout(PoliticaConfigAdic);
        PoliticaConfigAdic.setLayout(PoliticaConfigAdicLayout);
        PoliticaConfigAdicLayout.setHorizontalGroup(
            PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliticaConfigAdicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PoliticaConfigAdicLayout.createSequentialGroup()
                        .addComponent(txtCapMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCapMemoria))
                    .addGroup(PoliticaConfigAdicLayout.createSequentialGroup()
                        .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsigMemoria)
                            .addComponent(txtTimeQuantum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAsigMemoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnTimeQuantum)))))
        );
        PoliticaConfigAdicLayout.setVerticalGroup(
            PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliticaConfigAdicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimeQuantum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnTimeQuantum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsigMemoria)
                    .addComponent(cmbAsigMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PoliticaConfigAdicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapMemoria)
                    .addComponent(spnCapMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout PanelConfiguracionLayout = new javax.swing.GroupLayout(PanelConfiguracion);
        PanelConfiguracion.setLayout(PanelConfiguracionLayout);
        PanelConfiguracionLayout.setHorizontalGroup(
            PanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPoliticaPlanif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PoliticaConfigAdic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelConfiguracionLayout.setVerticalGroup(
            PanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConfiguracionLayout.createSequentialGroup()
                .addGroup(PanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PoliticaConfigAdic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(PanelPoliticaPlanif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProcesos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(PanelSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelSimulacion.getAccessibleContext().setAccessibleDescription("");

        PanelColaProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));
        PanelColaProcesos.setLayout(new java.awt.BorderLayout());

        ColaProcesos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        ScrollColaProcesos.setViewportView(ColaProcesos);

        PanelColaProcesos.add(ScrollColaProcesos, java.awt.BorderLayout.CENTER);

        PanelMemoriaRAM.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria RAM"));

        MemoriaRAM.setLayout(new javax.swing.BoxLayout(MemoriaRAM, javax.swing.BoxLayout.LINE_AXIS));
        ScrollMemoriaRAM.setViewportView(MemoriaRAM);

        javax.swing.GroupLayout PanelMemoriaRAMLayout = new javax.swing.GroupLayout(PanelMemoriaRAM);
        PanelMemoriaRAM.setLayout(PanelMemoriaRAMLayout);
        PanelMemoriaRAMLayout.setHorizontalGroup(
            PanelMemoriaRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollMemoriaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelMemoriaRAMLayout.setVerticalGroup(
            PanelMemoriaRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollMemoriaRAM, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );

        PanelEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Estadisticas CPU"));

        lblTiempoUso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTiempoUso.setText("0");

        lblTiempoOcioso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTiempoOcioso.setText("0");

        lblTiempoEspProm.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTiempoEspProm.setText("0");

        lblDuracion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblDuracion.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Tiempo de Uso:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Tiempo ocioso:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Tiempo de Espera Promedio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Duracion:");

        PanelLeyendaProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leyenda de Procesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        LeyendaEjec.setBackground(Color.GREEN);
        LeyendaEjec.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LeyendaEjec.setPreferredSize(new java.awt.Dimension(13, 13));

        javax.swing.GroupLayout LeyendaEjecLayout = new javax.swing.GroupLayout(LeyendaEjec);
        LeyendaEjec.setLayout(LeyendaEjecLayout);
        LeyendaEjecLayout.setHorizontalGroup(
            LeyendaEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        LeyendaEjecLayout.setVerticalGroup(
            LeyendaEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Ejecutando");

        LeyendoListos.setBackground(Color.YELLOW);
        LeyendoListos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LeyendoListos.setPreferredSize(new java.awt.Dimension(13, 13));

        javax.swing.GroupLayout LeyendoListosLayout = new javax.swing.GroupLayout(LeyendoListos);
        LeyendoListos.setLayout(LeyendoListosLayout);
        LeyendoListosLayout.setHorizontalGroup(
            LeyendoListosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        LeyendoListosLayout.setVerticalGroup(
            LeyendoListosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Listos");

        LeyendaBloqueados.setBackground(Color.PINK);
        LeyendaBloqueados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout LeyendaBloqueadosLayout = new javax.swing.GroupLayout(LeyendaBloqueados);
        LeyendaBloqueados.setLayout(LeyendaBloqueadosLayout);
        LeyendaBloqueadosLayout.setHorizontalGroup(
            LeyendaBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        LeyendaBloqueadosLayout.setVerticalGroup(
            LeyendaBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Bloqueado");

        LeyendaFinalizados.setBackground(Color.BLUE);
        LeyendaFinalizados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LeyendaFinalizados.setPreferredSize(new java.awt.Dimension(13, 13));

        javax.swing.GroupLayout LeyendaFinalizadosLayout = new javax.swing.GroupLayout(LeyendaFinalizados);
        LeyendaFinalizados.setLayout(LeyendaFinalizadosLayout);
        LeyendaFinalizadosLayout.setHorizontalGroup(
            LeyendaFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        LeyendaFinalizadosLayout.setVerticalGroup(
            LeyendaFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Finalizados");

        LeyendaError.setBackground(Color.RED);
        LeyendaError.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LeyendaError.setPreferredSize(new java.awt.Dimension(13, 13));

        javax.swing.GroupLayout LeyendaErrorLayout = new javax.swing.GroupLayout(LeyendaError);
        LeyendaError.setLayout(LeyendaErrorLayout);
        LeyendaErrorLayout.setHorizontalGroup(
            LeyendaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        LeyendaErrorLayout.setVerticalGroup(
            LeyendaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Error");
        jLabel10.setPreferredSize(new java.awt.Dimension(13, 13));

        javax.swing.GroupLayout PanelLeyendaProcesosLayout = new javax.swing.GroupLayout(PanelLeyendaProcesos);
        PanelLeyendaProcesos.setLayout(PanelLeyendaProcesosLayout);
        PanelLeyendaProcesosLayout.setHorizontalGroup(
            PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeyendaEjec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(LeyendaBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(LeyendoListos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                        .addGroup(PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LeyendaError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(LeyendaFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLeyendaProcesosLayout.setVerticalGroup(
            PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeyendaProcesosLayout.createSequentialGroup()
                .addGroup(PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeyendaEjec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeyendaBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(LeyendoListos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLeyendaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeyendaError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeyendaFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelEstadisticasLayout = new javax.swing.GroupLayout(PanelEstadisticas);
        PanelEstadisticas.setLayout(PanelEstadisticasLayout);
        PanelEstadisticasLayout.setHorizontalGroup(
            PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                        .addComponent(PanelLeyendaProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                        .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblTiempoUso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTiempoOcioso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTiempoEspProm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelEstadisticasLayout.setVerticalGroup(
            PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTiempoUso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTiempoOcioso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTiempoEspProm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLeyendaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelSistemaOperativoLayout = new javax.swing.GroupLayout(PanelSistemaOperativo);
        PanelSistemaOperativo.setLayout(PanelSistemaOperativoLayout);
        PanelSistemaOperativoLayout.setHorizontalGroup(
            PanelSistemaOperativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistemaOperativoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(PanelSistemaOperativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMemoriaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSistemaOperativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSistemaOperativoLayout.createSequentialGroup()
                            .addComponent(PanelColaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelSistemaOperativoLayout.setVerticalGroup(
            PanelSistemaOperativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistemaOperativoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(PanelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSistemaOperativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelColaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMemoriaRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneSO.addTab("Sistema Operativo", PanelSistemaOperativo);

        PanelEjecutando.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejecutando"));

        tblEjec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PC", "Memoria", "Prioridad", "Progreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollEjecutando.setViewportView(tblEjec);

        javax.swing.GroupLayout PanelEjecutandoLayout = new javax.swing.GroupLayout(PanelEjecutando);
        PanelEjecutando.setLayout(PanelEjecutandoLayout);
        PanelEjecutandoLayout.setHorizontalGroup(
            PanelEjecutandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEjecutandoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollEjecutando, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelEjecutandoLayout.setVerticalGroup(
            PanelEjecutandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjecutandoLayout.createSequentialGroup()
                .addComponent(ScrollEjecutando, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        PanelListos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listos"));

        tblListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PC", "Memoria", "Prioridad", "Progreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollListos.setViewportView(tblListos);

        javax.swing.GroupLayout PanelListosLayout = new javax.swing.GroupLayout(PanelListos);
        PanelListos.setLayout(PanelListosLayout);
        PanelListosLayout.setHorizontalGroup(
            PanelListosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollListos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelListosLayout.setVerticalGroup(
            PanelListosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollListos, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelBloqueados.setBorder(javax.swing.BorderFactory.createTitledBorder("Bloqueados"));

        tblBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PC", "Memoria", "Prioridad", "Progreso", "Disp. Interrupcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollBloqueados.setViewportView(tblBloqueados);

        javax.swing.GroupLayout PanelBloqueadosLayout = new javax.swing.GroupLayout(PanelBloqueados);
        PanelBloqueados.setLayout(PanelBloqueadosLayout);
        PanelBloqueadosLayout.setHorizontalGroup(
            PanelBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBloqueadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBloqueadosLayout.setVerticalGroup(
            PanelBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBloqueadosLayout.createSequentialGroup()
                .addComponent(ScrollBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        Flecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FlechaTablaDerecha.png"))); // NOI18N

        Flecha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FlechaTablaDiagonalIzquierda.png"))); // NOI18N

        Flecha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FlechaTablaIzquierda.png"))); // NOI18N

        Flecha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FlechaTablaDiagonalDerecha.png"))); // NOI18N

        PanelFinalizados.setBorder(javax.swing.BorderFactory.createTitledBorder("Finalizados"));

        tblFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PCError", "Memoria"
            }
        ));
        ScrollFinalizados.setViewportView(tblFinal);

        javax.swing.GroupLayout PanelFinalizadosLayout = new javax.swing.GroupLayout(PanelFinalizados);
        PanelFinalizados.setLayout(PanelFinalizadosLayout);
        PanelFinalizadosLayout.setHorizontalGroup(
            PanelFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollFinalizados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelFinalizadosLayout.setVerticalGroup(
            PanelFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollFinalizados, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FlechaTablaDiagonalCurva.png"))); // NOI18N

        javax.swing.GroupLayout PanelTablasProcesosLayout = new javax.swing.GroupLayout(PanelTablasProcesos);
        PanelTablasProcesos.setLayout(PanelTablasProcesosLayout);
        PanelTablasProcesosLayout.setHorizontalGroup(
            PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(PanelBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                        .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelListos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Flecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Flecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(Flecha4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelEjecutando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Flecha3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelTablasProcesosLayout.setVerticalGroup(
            PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                        .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                                .addGroup(PanelTablasProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                                        .addComponent(Flecha1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Flecha2))
                                    .addComponent(PanelListos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Flecha4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTablasProcesosLayout.createSequentialGroup()
                                .addComponent(PanelEjecutando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Flecha3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTablasProcesosLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        TabbedPaneSO.addTab("Tablas de Procesos", PanelTablasProcesos);

        PanelProcesosEjecutados.setBorder(javax.swing.BorderFactory.createTitledBorder("Historico de Procesos Ejecutados"));

        tblHistEjec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PC", "Memoria", "Prioridad", "Progreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollHistoricoEjec.setViewportView(tblHistEjec);

        javax.swing.GroupLayout PanelProcesosEjecutadosLayout = new javax.swing.GroupLayout(PanelProcesosEjecutados);
        PanelProcesosEjecutados.setLayout(PanelProcesosEjecutadosLayout);
        PanelProcesosEjecutadosLayout.setHorizontalGroup(
            PanelProcesosEjecutadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosEjecutadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollHistoricoEjec, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProcesosEjecutadosLayout.setVerticalGroup(
            PanelProcesosEjecutadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosEjecutadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollHistoricoEjec)
                .addContainerGap())
        );

        PanelProcesosBloqueados.setBorder(javax.swing.BorderFactory.createTitledBorder("Historico de Procesos Bloqueados"));

        tblHistBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PC", "Memoria", "Prioridad", "Progreso", "Dispositivo de Interrupcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollHistoricoBloqueados.setViewportView(tblHistBloqueados);

        javax.swing.GroupLayout PanelProcesosBloqueadosLayout = new javax.swing.GroupLayout(PanelProcesosBloqueados);
        PanelProcesosBloqueados.setLayout(PanelProcesosBloqueadosLayout);
        PanelProcesosBloqueadosLayout.setHorizontalGroup(
            PanelProcesosBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosBloqueadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollHistoricoBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProcesosBloqueadosLayout.setVerticalGroup(
            PanelProcesosBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosBloqueadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollHistoricoBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelTablaProcesosHistoricoLayout = new javax.swing.GroupLayout(PanelTablaProcesosHistorico);
        PanelTablaProcesosHistorico.setLayout(PanelTablaProcesosHistoricoLayout);
        PanelTablaProcesosHistoricoLayout.setHorizontalGroup(
            PanelTablaProcesosHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaProcesosHistoricoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PanelProcesosEjecutados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelProcesosBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelTablaProcesosHistoricoLayout.setVerticalGroup(
            PanelTablaProcesosHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaProcesosHistoricoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelTablaProcesosHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelProcesosBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProcesosEjecutados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        TabbedPaneSO.addTab("Historico de Tablas de Procesos", PanelTablaProcesosHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPaneSO, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneSO)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnTimeQuantumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTimeQuantumStateChanged
        t.stop();
        so.parar();
        int nq = (int)spnTimeQuantum.getValue();
        so.setQuantum(nq);
        if(encendido){
            t.start();
            so.iniciar();
        }
    }//GEN-LAST:event_spnTimeQuantumStateChanged

    private void spnCapMemoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCapMemoriaStateChanged
        t.stop();
        so.parar();
        int ncm = (int)spnCapMemoria.getValue();
        so.cambiarCapMemoria(ncm);
        PanelMemoriaRAM.setBorder(BorderFactory.createTitledBorder("RAM "+ncm+"MB"));
        if(encendido){
            t.start();
            so.iniciar();
        }
    }//GEN-LAST:event_spnCapMemoriaStateChanged

    private void cmbAsigMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsigMemoriaActionPerformed
        so.setAsignacionMemoria(cmbAsigMemoria.getSelectedIndex());
    }//GEN-LAST:event_cmbAsigMemoriaActionPerformed

    private void cmbTipoPoliticaPlanifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPoliticaPlanifActionPerformed
        so.setApropiativa(cmbTipoPoliticaPlanif.getSelectedIndex()==0);
    }//GEN-LAST:event_cmbTipoPoliticaPlanifActionPerformed

    private void cmbAlgoritmoPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmoPlanificacionActionPerformed
        t.stop();
        so.parar();
        so.setPolitica(cmbAlgoritmoPlanificacion.getSelectedIndex());
        if(cmbAlgoritmoPlanificacion.getSelectedIndex()==2){
            spnTimeQuantum.setEnabled(true);
        }
        else{
            spnTimeQuantum.setEnabled(false);
        }
        if(encendido){
            t.start();
            so.iniciar();
        }
    }//GEN-LAST:event_cmbAlgoritmoPlanificacionActionPerformed

    private void btnAddProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProcesoActionPerformed
        try {
            int bt = Integer.parseInt(txtBurstTime.getText());
            if(so.crearProcesoPersonalizado(bt)){
                System.out.println("Se creo nuevo proceso personalizado");
                so.graficarColaProcesos(ColaProcesos,tblEjec,tblListos,tblBloqueados,tblFinal,tblHistEjec,tblHistBloqueados);
                //so.pintarListos(jpListos);
                txtPID.setText(Proceso.numeroProcesos+"");
                validate();
            }else{
                System.out.println("No se pudo crear nuevo proceso");
                //jlErrorNuevoProceso.setText("Nivel de multiprogramación: "+SO.maxCantProcesos);
            }
        } catch (NumberFormatException e) {
            //jlErrorNuevoProceso.setText("Introducir un entero");
            System.out.println("Numero no valido");
        }
    }//GEN-LAST:event_btnAddProcesoActionPerformed

    private void btnPlayStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayStopActionPerformed
        iniciarSimulacion();
    }//GEN-LAST:event_btnPlayStopActionPerformed

    private void sldVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVelocidadStateChanged
        System.out.println("Velocidad: "+sldVelocidad.getValue()+ "%");
        delay = 101 - sldVelocidad.getValue();
        t.setDelay(delay);
        so.cambiarDelay(delay);
        u.setDelay(delay);
    }//GEN-LAST:event_sldVelocidadStateChanged

    private void chbValoresAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbValoresAleatoriosActionPerformed
        if(chbValoresAleatorios.isSelected()){
            u.iniciar();
        }else{
            u.parar();
        }
    }//GEN-LAST:event_chbValoresAleatoriosActionPerformed
    
    @Override
    public void setVisible(boolean bln) {
        super.setVisible(bln);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColaProcesos;
    private javax.swing.JLabel Flecha1;
    private javax.swing.JLabel Flecha2;
    private javax.swing.JLabel Flecha3;
    private javax.swing.JLabel Flecha4;
    private javax.swing.JPanel LeyendaBloqueados;
    private javax.swing.JPanel LeyendaEjec;
    private javax.swing.JPanel LeyendaError;
    private javax.swing.JPanel LeyendaFinalizados;
    private javax.swing.JPanel LeyendoListos;
    private javax.swing.JPanel MemoriaRAM;
    private javax.swing.JPanel PanelBloqueados;
    private javax.swing.JPanel PanelColaProcesos;
    private javax.swing.JPanel PanelConfiguracion;
    private javax.swing.JPanel PanelEjecutando;
    private javax.swing.JPanel PanelEstadisticas;
    private javax.swing.JPanel PanelFinalizados;
    private javax.swing.JPanel PanelLeyendaProcesos;
    private javax.swing.JPanel PanelListos;
    private javax.swing.JPanel PanelMemoriaRAM;
    private javax.swing.JPanel PanelPoliticaPlanif;
    private javax.swing.JPanel PanelProcesos;
    private javax.swing.JPanel PanelProcesosBloqueados;
    private javax.swing.JPanel PanelProcesosEjecutados;
    private javax.swing.JPanel PanelSimulacion;
    private javax.swing.JPanel PanelSistemaOperativo;
    private javax.swing.JPanel PanelTablaProcesosHistorico;
    private javax.swing.JPanel PanelTablasProcesos;
    private javax.swing.JPanel PanelVelocidadSimulacion;
    private javax.swing.JPanel PoliticaConfigAdic;
    private javax.swing.JScrollPane ScrollBloqueados;
    private javax.swing.JScrollPane ScrollColaProcesos;
    private javax.swing.JScrollPane ScrollEjecutando;
    private javax.swing.JScrollPane ScrollFinalizados;
    private javax.swing.JScrollPane ScrollHistoricoBloqueados;
    private javax.swing.JScrollPane ScrollHistoricoEjec;
    private javax.swing.JScrollPane ScrollListos;
    private javax.swing.JScrollPane ScrollMemoriaRAM;
    private javax.swing.JTabbedPane TabbedPaneSO;
    private javax.swing.JButton btnAddProceso;
    private javax.swing.JButton btnPlayStop;
    private javax.swing.JCheckBox chbValoresAleatorios;
    private javax.swing.JComboBox<String> cmbAlgoritmoPlanificacion;
    private javax.swing.JComboBox<String> cmbAsigMemoria;
    private javax.swing.JComboBox<String> cmbTipoPoliticaPlanif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAlgoritmoPlanificacion;
    private javax.swing.JLabel lblBursTime;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblPID;
    private javax.swing.JLabel lblTiempoEspProm;
    private javax.swing.JLabel lblTiempoOcioso;
    private javax.swing.JLabel lblTiempoUso;
    private javax.swing.JLabel lblTipoPolitica;
    private javax.swing.JSlider sldVelocidad;
    private javax.swing.JSpinner spnCapMemoria;
    private javax.swing.JSpinner spnTimeQuantum;
    private javax.swing.JTable tblBloqueados;
    private javax.swing.JTable tblEjec;
    private javax.swing.JTable tblFinal;
    private javax.swing.JTable tblHistBloqueados;
    private javax.swing.JTable tblHistEjec;
    private javax.swing.JTable tblListos;
    private javax.swing.JLabel txtAsigMemoria;
    private javax.swing.JTextField txtBurstTime;
    private javax.swing.JLabel txtCapMemoria;
    private javax.swing.JTextField txtPID;
    private javax.swing.JLabel txtTimeQuantum;
    // End of variables declaration//GEN-END:variables

}
